### ISSUE TITLE
Partial link styling in custom epub.css is overridden by ebook defaults.

### ISSUE THREAD

**Issue by jachiang** [asciidoctor/asciidoctor-epub3#182]
I have a document with many links in the body, and therefore having many underlined links make the text unwieldy to read. One solution is to restyle the links as italics for example (in epub3.css), and attempt to remove the underlining.

```css
  /* Modified epub3.css in local css folder */

a {
  background: transparent;

  /* Custom link styling */
  font-style: italic;
  text-decoration: none;
}
```
And build with:
```
$ asciidoctor-epub3 -a epub3-stylesdir=css@ master-epub.asciidoc
```
Although the italic font-style will take effect in iBooks or Kindle Previewer3, all links remain underlined. Given the experience of creating the `epub3`, `epub3-css-only` style sheets, I wonder whether the maintainers of this project know if is possible to style links in ebook readers without these attributes being overriden in the ebook reader? Many thanks!

**Comment by slonopotamus** [comment]
My Google-fu and some experiments say that it is impossible to disable link underlining on Kindle.

There's underlining even with the following CSS:

```css
a         { text-decoration: none !important; }
a:link    { text-decoration: none !important; }
a:visited { text-decoration: none !important; }
a:hover   { text-decoration: none !important; }
a:active  { text-decoration: none !important; }
```
