### ISSUE TITLE
Use darker font color on e-ink devices (Kindle Paperwhite)

### ISSUE THREAD

**Issue by cexbrayat** [asciidoctor/asciidoctor-epub3#67]
We just released our [ebook](https://books.ninja-squad.com/angular2), and some readers have been complaining about our font (on Kindle and Kobo) that is too light.

It is indeed a light gray, and we were wondering if there is an easy way to customize the font color for something a bit darker.
Going over the docs, I did not find what would be the best way and my attempt has not yield any result.

Do we need to have a custom `epub3.css` file?
Can I just overwrite the font color, or do I need to take the whole existing `epub3.css` content?

**Comment by mojavelinux** [comment]
I've also heard several complaints that the text color is too light, so I'm definitely willing to change the default. It's currently set to `#333332`. Perhaps we should switch to the value used in the default Asciidoctor stylesheet, which is `#262626`. I'd even consider going to `#2222222`. The key will be nailing down the right color.

The way to override the styles at the moment is to provide a custom epub3.css file, which I realize is a bit heavy.

**Comment by mojavelinux** [comment]
Screenshots would really help here.

**Comment by mojavelinux** [comment]
The real problem seems to be non-color devices (which don't show gray the same). We could set the color to an even dark black on those devices by using a CSS3 media query. See https://developer.mozilla.org/en-US/docs/Web/CSS/Media_Queries/Using_media_queries#Media_features

**Comment by mojavelinux** [comment]
Black is just horrible when displayed on a LCD with a fluorescent backlight (any color device).

**Comment by clacote** [comment]
@mojavelinux You were asking for picture. One of the reader complaining of the too light grey on his Kindle provided a picture: 
![kindle](https://cloud.githubusercontent.com/assets/750715/12564690/eb7decee-c3b0-11e5-9eab-d2bf7b7b7b5b.png)

**Comment by mojavelinux** [comment]
Yep, I saw that after I posted. Hopefully the reader will be willing to
post an "after" picture as well so we can see the difference.

**Comment by cexbrayat** [comment]
For the record, the workaround is:

- adding the `epub3.css` and `epub3-css3-only.css` files to the project (for example in a directory `styles`)
- including them in the document with `:epub3-stylesdir: styles`
- override the font color to be pure black `#000000`

With this it should display fine on Paperwhite for example.

**Comment by mojavelinux** [comment]
The Paperwhite already solves the problem at the hardware level of pure black being hard/harsh to read We don't need to help it (because then the text becomes too dim). The reason we use the dark gray is to fix over-saturation on color devices (like the Kindle Fire). We should use a media query to detect this scenario and apply the appropriate styles.

**Comment by mojavelinux** [comment]
We'll need to run a test like the one described in this article to see what matches for the Paperwhite so we know what media query to use.

http://epubsecrets.com/media-queries-in-epubs.php

**Comment by mojavelinux** [comment]
(when I say Paperwhite, I'm referring to all devices like it, including the Kobo).

**Comment by clacote** [comment]
The same user who was complaining of low contrast is now happy with the pure black workaround. He sent a new capture:
![kindle-after](https://cloud.githubusercontent.com/assets/750715/12606944/8d2ace88-c4d1-11e5-8648-2af8f9fe2fcc.png)

**Comment by mojavelinux** [comment]
Very nice! Thanks for the follow-up @clacote. I have a solid understanding of the issue at hand now.

**Comment by mojavelinux** [comment]
I keep wanting to fix this issue by using a monochrome media query. Sadly, the device that media query doesn't work on is the Kindle Paperwhite :(

It looks like to fix this in core (and still use dark gray for color devices) we have to use media queries based on screen sizes. (Honestly, what is this world coming to?)

For details, see https://medium.com/@sandersk/responsive-ebook-design-a-primer-8bba01328219#7be5.

Something like:

```css
/* Use dark fonts on Kindle Paperwhite */
@media amzn-kf8 and (device-height: 1024px) and (device-width: 758px) {
  body p,
  body a:link,
  ul, ol, li, dl, dt, dd, footer,
  div.verse .attribution, table.table th, table.table td,
  figcaption, caption,
  h1, h2, h3, h4, h5 {
    color: #000000;
  }

  body a:link {
    -webkit-text-fill-color: #000000;
  }
  
  .chapter-header {
    background-color: #191918;
  }
}
```

I don't have a Kindle Paperwhite, so I'd need someone to verify this proposal works both in portrait and landscape mode.

**Comment by PrimaryFeather** [comment]
I just tested this on two Kindle Paperwhites from 2012 and 2014, and it works just fine in portrait mode. To get it to work in landscape, as well, I had to change the query like this:

```css
@media amzn-kf8 and (device-height: 1024px) and (device-width:  758px),
       amzn-kf8 and (device-height:  758px) and (device-width: 1024px) {
    /* ... */
}
```

Furthermore, I also included `div.abstract > p` in the list of elements that need to use pure black. With these changes, the output looked really great on the display.

(Before, the gray looked kind of washed out, like a bleached photocopy. Not pleasant to read!)

So, in my opinion, a must-have for the current style sheet! :wink: 👍

**Comment by PrimaryFeather** [comment]
If you want, I can send you a pull request — but it's really just a matter of copying the code from above into the style sheet. Just let me know how you'd like to do it! 😄

**Comment by mojavelinux** [comment]
I'll go ahead and apply these changes for alpha.8 so you can test.

Here's what I'm going to add:

```css
/* Use dark fonts on Kindle Paperwhite */
@media amzn-kf8 and (device-height: 1024px) and (device-width: 758px),
    amzn-kf8 and (device-height:  758px) and (device-width: 1024px) {
  body p,
  div.abstract > p,
  body a:link,
  ul, ol, li, dl, dt, dd, footer,
  div.verse .attribution, table.table th, table.table td,
  figcaption, caption,
  h1.chapter-title .subtitle,
  h1, h2, h3, h4, h5 {
    color: #000000;
  }

  body a:link {
    -webkit-text-fill-color: #000000;
  }
  
  h1.chapter-title {
    color: #191918;
    border-bottom-color: #191918;
  }
}
```
